"""empty message

Revision ID: 281489f1adb0
Revises: 896a153b9f6c
Create Date: 2021-06-30 11:53:46.383469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281489f1adb0'
down_revision = '896a153b9f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'website_link')
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
