"""empty message

Revision ID: a35c096f4326
Revises: d7bebd1aa7a3
Create Date: 2021-06-30 10:39:21.855269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35c096f4326'
down_revision = 'd7bebd1aa7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres3', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genres')
    op.add_column('venue', sa.Column('genres3', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('venue', 'genres3')
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('artist', 'genres3')
    # ### end Alembic commands ###
