"""empty message

Revision ID: c68e79dd8cd8
Revises: 46e4e6f50bf6
Create Date: 2021-07-02 10:30:05.896642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68e79dd8cd8'
down_revision = '46e4e6f50bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('worthless_column', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'worthless_column')
    # ### end Alembic commands ###
